nf-core/circdna update to v1.0.2
nf-core/circdna pull request #46
Opened 2023-03-07 13:36 UTC by DSchreyer

# Nf-core/circdna Update to v.1.0.2
This pull requests contains:
- bug fixes to current local modules
- updates to nf-core modules
- updates to local modules
- Added new functionality to AmpliconArchitect branch
- Updated to nf-core template 2.71
- Fixed nextflow.config bugs
- Updated README.md
- 

## PR checklist

- [x ] This comment contains a description of changes (with reason).
- [ x] If you've fixed a bug or added code that should be tested, add tests!
  - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/circdna/tree/master/.github/CONTRIBUTING.md)
  - [ ] If necessary, also make a PR on the nf-core/circdna _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ x] Make sure your code lints (`nf-core lint`).
- [x ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ x] Usage Documentation in `docs/usage.md` is updated.
- [x ] Output Documentation in `docs/output.md` is updated.
- [x ] `CHANGELOG.md` is updated.
- [x ] `README.md` is updated (including new tool citations and authors/contributors).

2023-03-08 11:24 UTC, sguizard requested changes
Very clean code, nicely commented. 
Some minor corrections needed, otherwise LGTM for me.

2023-03-08 11:24 UTC, sguizard commented on subworkflows/local/bam_markduplicates_picard/meta.yml
> +
Missing fai input

2023-03-08 11:24 UTC, sguizard commented on subworkflows/local/bam_markduplicates_picard/meta.yml
> +output:
Missing bam and metrics outputs

2023-03-09 07:43 UTC, sguizard approved these changes
OK for me.

2023-03-09 07:43 UTC, sguizard commented on subworkflows/local/bam_markduplicates_picard/meta.yml
> +    pattern: "*.{fai}"
```suggestion
      type: file
      description: Reference genome fasta index file
      pattern: "*.{fai}"
```

2023-03-09 07:43 UTC, sguizard commented on subworkflows/local/bam_markduplicates_picard/meta.yml
> +    pattern: "*.{bam}"
```suggestion
      type: file
      description: BAM file with duplicate reads marked/removed
      pattern: "*.{bam}"
```

2023-03-09 08:57 UTC, yuukiiwa approved these changes
Thanks, @DSchreyer! Looks good to me! Just a very small comment for CHANGELOG.md

2023-03-09 08:57 UTC, yuukiiwa commented on CHANGELOG.md
> +- AmpliconClassifier MakeInput and MakeResultsTable process
It will be great if softwares/functions are indicated as code for clarity:

`AmpliconClassifier` `MakeInput` and `MakeResultsTable` process

2023-03-09 10:12 UTC, DSchreyer commented on subworkflows/local/bam_markduplicates_picard/meta.yml
> +    pattern: "*.{fai}"
Resolved

2023-03-09 11:03 UTC, merged