v.1.0.3  - Minor release with updated documentation and test runs
nf-core/circdna pull request #51
Opened 2023-03-23 07:46 UTC by DSchreyer

## v1.0.3 - [2023-03-23]

### `Added`

- documentation about absolute path needed of AmpliconArchitect data repository
- ampliconclassifier stub run tests
- new version of circdna metromap with updated colors
- note that ATAC-seq should be used in caution with the pipeline.

### `Fixed`

### `Dependencies`

### `Deprecated`

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/circdna/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/circdna _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2023-05-26 18:16 UTC, SPPearce requested changes
I think this is generally fine.
Can you go through the scripts and check that they have authors and licences please.
See: https://nf-co.re/docs/contributing/pipeline_release_review_guidelines

2023-05-26 18:16 UTC, SPPearce commented on bin/check_reference.py
Can you please add an author and licence to this script please.

2023-05-26 18:16 UTC, SPPearce commented on bin/cnv_prefilter.py
And this one.

2023-05-26 18:16 UTC, SPPearce commented on modules/local/ampliconsuite/prepareaa.nf
> +        'https://depot.gala3hhhhhhhhhorg/singularity/mulled-v2-6eefa51f13933d65b4f8155ca2f8cd81dea474ba:baa777f7c4e89a2ec4d1eab7d424a1f46503bac7-0':
What is going on here?

2023-05-26 18:16 UTC, SPPearce commented on modules/local/ampliconsuite/prepareaa.nf
> -    conda "conda-forge::python=2.7 bioconda::pysam=0.15.2 anaconda::flask=1.1.2 anaconda::cython=0.29.14 anaconda::numpy=1.16.6 anaconda::scipy=1.2.1 conda-forge::matplotlib=2.2.5 mosek::mosek=8.0.60
Changing from python 2 to python 3 is a major change isn't it (I'm not a python developer)? Does the script still work?

2023-05-26 18:16 UTC, SPPearce commented on modules/local/amplified_intervals.nf
> +    conda "conda-forge::python=2.7 bioconda::pysam=0.15.2 anaconda::flask=1.1.2 anaconda::cython=0.29.14 anaconda::numpy=1.16.6 anaconda::scipy=1.2.1 conda-forge::matplotlib=2.2.5 mosek::mosek=8.0.60
This script hasn't been updated for the newer versions, but the previous one has?

2023-05-26 19:56 UTC, jluebeck commented on modules/local/ampliconsuite/prepareaa.nf
> -    conda "conda-forge::python=2.7 bioconda::pysam=0.15.2 anaconda::flask=1.1.2 anaconda::cython=0.29.14 anaconda::numpy=1.16.6 anaconda::scipy=1.2.1 conda-forge::matplotlib=2.2.5 mosek::mosek=8.0.60
Hi Simon, I'm the developer of PrepareAA -  a while back we added support for both python2 and python3 to this collection of tools, so it can be run with either version of python.

2023-05-26 20:02 UTC, jluebeck commented on bin/amplified_intervals.py
> +tempL = []
Looks like this change actually makes circdna's modified version of amplified_intervals.py closer to the current version of the amplified_intervals.py script from the AmpliconArchitect maintainer (me). Is it possible to use the unmodified version of amplified_intervals.py script directly from the jluebeck fork of AmpliconArchitect? This way it can be kept updated more easily.

2023-05-27 19:47 UTC, SPPearce commented on bin/amplified_intervals.py
> +tempL = []
Hmm. It sounds like the easiest things would be if AmpliconArchitect was put into bioconda. Then these additional helper scripts would just be in the containers and not separate scripts in the pipeline.

2023-05-27 23:16 UTC, jluebeck commented on bin/amplified_intervals.py
> +tempL = []
Got it - we are planning to work on this, but I will prioritize it.

2023-05-28 06:24 UTC, SPPearce commented on bin/amplified_intervals.py
> +tempL = []
Great! On the nf-core slack there is a `bioconda` channel if you need help/reviews with that.

2023-05-30 06:16 UTC, DSchreyer commented on modules/local/ampliconsuite/prepareaa.nf
> +        'https://depot.gala3hhhhhhhhhorg/singularity/mulled-v2-6eefa51f13933d65b4f8155ca2f8cd81dea474ba:baa777f7c4e89a2ec4d1eab7d424a1f46503bac7-0':
Oh interesting. Yes I will change that. PrepareAA is not usable atm without its own container so it won't cause a bug until it is in the pipeline. Thanks for spotting

2023-05-30 06:20 UTC, DSchreyer commented on bin/amplified_intervals.py
> +tempL = []
Hi Simon and Jens, Yes I will update the pipeline with the unmodified version of the script on your fork and add citations and version

2023-05-30 06:27 UTC, DSchreyer commented on modules/local/ampliconsuite/prepareaa.nf
> -    conda "conda-forge::python=2.7 bioconda::pysam=0.15.2 anaconda::flask=1.1.2 anaconda::cython=0.29.14 anaconda::numpy=1.16.6 anaconda::scipy=1.2.1 conda-forge::matplotlib=2.2.5 mosek::mosek=8.0.60
Hi Simon and Jens, 
I will update the prepareaa.nf containers from python2 and python3 and it works with both. PrepareAA is not yet included in the pipeline, but will be in the next version update. PrepareAA requires a new docker container which hopefully is automatically built after this version release. Then, prepareaa will be included and replaces the helper scripts `collect_seeds.nf` or `amplified_intervals.nf`

2023-05-30 07:18 UTC, DSchreyer commented on modules/local/amplified_intervals.nf
> +    conda "conda-forge::python=2.7 bioconda::pysam=0.15.2 anaconda::flask=1.1.2 anaconda::cython=0.29.14 anaconda::numpy=1.16.6 anaconda::scipy=1.2.1 conda-forge::matplotlib=2.2.5 mosek::mosek=8.0.60
Hi Simon, 
good spot. I will leave it as is for now and will update in the next version. It will get removed in the next version as it will be replaced by PrepareAA. The versions need to be cautiously handled as these packages don't have a lot of overlap where all can be simultaneously installed. Because it is working as is I am preferring to stay at the current version

2023-05-30 11:21 UTC, DSchreyer commented
Hi @jluebeck and @SPPearce ,
About the pipeline update. I included your suggestions and updated the pipeline. 

PrepareAA is still not included and needs to be included as soon as the docker container was generated. @pditommaso noted that nextflow has a wave option to generate containers on-the-fly. I will try to include it in this release so I will wait to merge until it is clear how I can implement wave into the pipeline.

2023-05-30 16:05 UTC, jluebeck commented on modules/local/ampliconsuite/prepareaa.nf
> -    conda "conda-forge::python=2.7 bioconda::pysam=0.15.2 anaconda::flask=1.1.2 anaconda::cython=0.29.14 anaconda::numpy=1.16.6 anaconda::scipy=1.2.1 conda-forge::matplotlib=2.2.5 mosek::mosek=8.0.60
Hi Simon and Daniel,

I am working on making a Conda package which will wrap AmpliconSuite-pipeline (PrepareAA.py) and its modules - AmpliconArchitect and AmpliconClassifier. Hopefully will be able to release it by next week or so. I just joined the nf-core slack and circdna channel - happy to discuss there. May ask some questions about conda packages there as well. Thanks!

2023-05-30 16:17 UTC, jluebeck commented on README.md
Generally, "ecDNA" seems to be the preferred term as it captures both the large megabase-scale oncogene-carrying extrachromosomal circular DNAs, and also includes the small circular extrachromosomal DNAs (which the field studying them call "eccDNAs"). The terminology is a bit confusing and it is not official in any regards, but my suggestion is that using the term "ecDNAs" instead of "eccDNAs" may be slightly less confusing for those who are coming to use the methods in the context of cancer samples (probably the majority of users?).

2023-05-30 19:05 UTC, jluebeck approved these changes
Looks good from the AA side. To confirm - is the workflow now
1. start with a bam file
2. run PrepareAA.py to get AA_CNV_SEEDS.bed
3. run AmpliconArchitect on bam file + AA_CNV_SEEDS.bed
4. run the AmpliconClassification stages?

If so that is great - as calling amplified_intervals.py outside of the PrepareAA.py wrapper is not really supported and could cause issues.

2023-05-30 19:06 UTC, jluebeck commented on modules/local/ampliconclassifier/ampliconsimilarity.nf
It is my fault the distinction on these two functions is not more clear. I will work on improving our documentaiton.

2023-05-31 09:37 UTC, DSchreyer commented on README.md
In my understanding eccDNAs was supposed to be the term for all circular DNAs including the large amplified and the small ones. EcDNAs is mostly used when talking about large amplified ones found usually in cancer. It seems that this changes from lab to lab and I am not sure what abbreviation should be used from now. However, I agree that most users will most likely be interested in identifying amplified ecDNAs and therefore I will change eccDNAs to ecDNAs in the `README.md`

2023-05-31 09:56 UTC, DSchreyer commented on modules/local/ampliconclassifier/ampliconsimilarity.nf
Understood! This should be easily included in this release.

2023-05-31 10:10 UTC, DSchreyer commented on modules/local/ampliconclassifier/makeresultstable.nf
About `PrepareAA.py` i mentioned that it is not yet included in this release. AmpliconArchitect still runs with the external amplified intervals script and needs to be updated. However, I don't have a docker container for PrepareAA, yet, which includes `intervaltree`. I will try using the `wave` strategy from nextflow, but if not, a built-docker-image script is in place that should generate a docker container upon the next pipeline release (after this merge). 

After the docker container is created, `PrepareAA.py` can be fully implemented. This can be facilitated in a few days which then will be also released.

I will let you know if I was able to implement `wave`. If not, I hope you will be available after this release to verify the correct implementation of prepareaa and offer to review the pipeline again.

Thanks a lot for your time and wonderful insights"

2023-05-31 13:20 UTC, jluebeck commented on README.md
I see, perhaps if the cirdna workflow supports analysis of both the small and also megabase-scale ecDNA, then it may be worth putting that into information into the Readme and making it clear which modules are designed for either task. AA and its related tools are not at all designed for detection of small (< 5kbp) eccDNAs, only the large, amplified structures.

2023-05-31 15:06 UTC, DSchreyer commented on README.md
That seems like a good idea. Will include

2023-06-05 06:12 UTC, DSchreyer commented
@SPPearce Let me know if you identified issues or changes that need to be implemented. I hope I addressed all your change request for a version release. 

I now stopped using `wave` and have fallen back to docker when talking about PrepareAA. PrepareAA will not yet be implemented, but will be implemented in the next release which will hopefully follow soon after this one. The only issue is, as I mentioned before, the docker container that is required for it to fully function with singularity and docker.

2023-06-05 10:31 UTC, SPPearce commented
> @SPPearce Let me know if you identified issues or changes that need to be implemented. I hope I addressed all your change request for a version release.
> 
> I now stopped using `wave` and have fallen back to docker when talking about PrepareAA. PrepareAA will not yet be implemented, but will be implemented in the next release which will hopefully follow soon after this one. The only issue is, as I mentioned before, the docker container that is required for it to fully function with singularity and docker.

I think most of my comments will be best resolved once the whole of AmpliconArchitect is on bioconda, that'll move a lot of the scripts from the pipeline here to just being present in the container.

2023-06-05 10:32 UTC, SPPearce approved these changes

2023-06-05 11:29 UTC, merged

2023-06-05 11:29 UTC, DSchreyer commented
> > @SPPearce Let me know if you identified issues or changes that need to be implemented. I hope I addressed all your change request for a version release.
> > I now stopped using `wave` and have fallen back to docker when talking about PrepareAA. PrepareAA will not yet be implemented, but will be implemented in the next release which will hopefully follow soon after this one. The only issue is, as I mentioned before, the docker container that is required for it to fully function with singularity and docker.
> 
> I think most of my comments will be best resolved once the whole of AmpliconArchitect is on bioconda, that'll move a lot of the scripts from the pipeline here to just being present in the container.

I agree. Thanks for reviewing and all your suggestions!