Pipeline Relase Version 1.0.5
nf-core/circdna pull request #64
Opened 2024-01-09 19:39 UTC by DSchreyer

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/circdna/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/circdna _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [x] `README.md` is updated (including new tool citations and authors/contributors).

2024-01-11 19:42 UTC, jluebeck commented
I have tested the ampliconarchitect run mode using bam input and found AmpliconSuite to working as expected. Thanks Daniel!

2024-01-18 10:10 UTC, SPPearce requested changes
Some relevantly minor comments, mostly on the changelog.
I'm testing the code on some of my own data too, as I have been using `circdna` anyway.

2024-01-18 10:10 UTC, SPPearce commented on nextflow.config
> +    version         = '1.0.5'
Why is this only a patch version bump? 
This should be a minor release I think (`1.1.0`)

2024-01-18 10:10 UTC, SPPearce commented on CHANGELOG.md
> +## v1.0.5 - [2024-01-09]
As I note further down, I think this is v1.1.0.

2024-01-18 10:10 UTC, SPPearce commented on CHANGELOG.md
> +
Can I suggest that you explain in general what you have done here, these are very brief notes.
A lot of the software versions have also been updated, I'd say you don't necessarily have to have a table detailing them all ([but it is nice to have](https://github.com/nf-core/rnaseq/blob/b89fac32650aacc86fcda9ee77e00612a1d77066/CHANGELOG.md?plain=1#L46)), but please at least mention this has happened.

2024-01-18 12:29 UTC, maxulysse commented on .github/workflows/ci.yml
> +        # TODO nf-core: You can customise CI pipeline run tests as required
If this is done you can remove the comment

2024-01-18 12:31 UTC, maxulysse commented on bin/extract_circle_SV_reads.py
is this needed?

2024-01-19 07:09 UTC, jluebeck commented on docs/output.md
> +- `[SAMPLE]_finishing_flag.txt`
Thanks, Simon for reviewing the PR! 

The finish_flag.txt file exists primarily for non-nextflow users of AmpliconSuite-pipeline. The file only gets a "completed" status written to it if the AmpliconSuite-pipeline module completed without errors. Provides a quick and easy way for users (primarily outside nextflow) to see that everything finished without issues. I think it is unlikely that if there was a crash somewhere during AmpliconSuite-pipeline that the whole nextflow pipeline would also continue without crashing, but I suppose it is possible.

2024-01-30 08:04 UTC, DSchreyer commented on CHANGELOG.md
> +
Removed

2024-01-30 08:05 UTC, DSchreyer commented on CHANGELOG.md
> +
Thanks for noting that! Yeah, I agree. I now made the description more extensive and changed the pipeline version to v1.1 .

2024-01-30 08:06 UTC, DSchreyer commented on .github/workflows/ci.yml
> +        # TODO nf-core: You can customise CI pipeline run tests as required
Removed. Good spot

2024-01-30 08:09 UTC, DSchreyer commented on bin/bam2bam.py
Yeah, those are needed as the circlemap/realign module is using the scripts in /bin. The conda version of circle-map Realign has some bugs, which are fixed locally in the scripts, but the official software is not updated since 2 years. Therefore, this workaround with the local scripts works nicely

2024-01-30 08:09 UTC, DSchreyer commented on bin/extract_circle_SV_reads.py
Similar to bam2bam.py

2024-01-30 08:13 UTC, DSchreyer commented on conf/test.config
> +    aa_data_repo        = "workflows"
I removed those. I included a directory check and workflows always exists when the pipeline is run. This prevents the pipeline exit when running the test profile. However, the directories are only checked when running ampliconarchitect.

2024-01-30 08:32 UTC, DSchreyer commented on main.nf
> +    def String command = "nextflow run ${workflow.manifest.name} --input samplesheet.csv --genome GRCh37 -profile docker"
Yeah you are correct. This needs to be updated with all the essential parameters. The new description is now better and is up-to-date.

2024-01-30 08:33 UTC, DSchreyer commented on nextflow.config
> +    version         = '1.0.5'
Thanks Simon. I was not aware that a patch is 1.0.* and a minor release is 1.* . I now bumped the version to 1.1.

2024-02-01 08:53 UTC, SPPearce commented on modules/nf-core/multiqc/meta.yml
MultiQC is now a local module, except this meta file which is still here. 
Why is it now a local module, what has changed?

2024-02-01 08:55 UTC, SPPearce commented on CHANGELOG.md
> +## v1.1 - [2024-01-30]
Should this be v1.1.0? @maxulysse

2024-02-01 08:55 UTC, SPPearce commented on CHANGELOG.md
> +## v1.1 - [2024-01-30]
```suggestion
## v1.1 - [2024-02-01]
```

2024-02-01 08:57 UTC, SPPearce approved these changes
Just a minor point about the multiqc file still in modules/nf-core.
If you are slightly changing the multiqc module from the one in the modules repo, you can use a patch file rather than moving it into local.

2024-02-03 07:13 UTC, DSchreyer commented on CHANGELOG.md
> +## v1.1 - [2024-01-30]
I modified it to v1.1.0. You are correct

2024-02-04 20:02 UTC, jluebeck approved these changes

2024-02-10 08:59 UTC, merged